- name: change linux root password
  hosts: all
  gather_facts: no
  tasks:
    - name: Update Root user's Password
      user: 
        name: root
        update_password: always 
        password: $6$rounds=656000$i5UigTVvYP8lr9e3$afYm5rwAM58fgZgN9lfav0j.lqUIrXtJajZHHItmVraCnP/I1XDlQHsMWy6EEG5rKuJwVWqVwyTpQ1oXU1vx7/
