- name: change linux root password
  hosts: all
  gather_facts: no
  tasks:
    - name: Update Root user's Password
      user: 
        name: root
        update_password: always 
        password: $6$rounds=656000$.QI9oNk.VOr.dgrW$/oDMgPZ3dKDDl3RploxU/siXHIO2vtb4oIaGkwj9yw5LfqCnj10CUtSX/Y9RbxA2NXuR40Zk8leDqBr9mqC1M/
